version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: godwinekuma
      POSTGRES_PASSWORD: example
      POSTGRES_DB: invoiceapp
    ports:
      - "5432:5432"