# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Tests

on:
    pull_request:
        branches: [main, development, feat/**]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                redis-version: [6]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Redis Server in GitHub Actions
              uses: supercharge/redis-github-action@1.2.0
              with:
                  redis-version: ${{ matrix.redis-version }}

            - run: npm ci
            - run: npm run build --if-present
            - run: npm test

            - name: Collect code coverage
              run: npm run test:cov
            - uses: codecov/codecov-action@v2
              with:
                  files: ./coverage/unit/clover.xml
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: true
                  verbose: true
